sudo: required
services: 
  - docker

before_install:
  - docker build -t shaharx/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run shaharx/react-test npm test -- --coverage

after_success:
  - docker build -t shaharx/fsi-client ./client
  - docker build -t shaharx/fsi-nginx ./nginx
  - docker build -t shaharx/fsi-server ./server
  - docker build -t shaharx/fsi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push shaharx/fsi-client
  - docker push shaharx/fsi-nginx
  - docker push shaharx/fsi-server
  - docker push shaharx/fsi-worker
